- name: Configure Networking
  block:
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - hostapd
          - dnsmasq
        state: present
        update_cache: true
      become: true

    - name: Configure hostapd
      ansible.builtin.copy:
        src: files/hostapd.conf
        dest: /etc/hostapd/hostapd.conf
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Update /etc/default/hostapd to point to config file
      ansible.builtin.lineinfile:
        dest: /etc/default/hostapd
        regexp: '^DAEMON_CONF='
        line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
      become: true

    - name: Setup dnsmasq
      ansible.builtin.copy:
        src: files/dnsmasq.conf
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: DNSMasq hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts.dnsmasq
        create: yes
        line: '10.0.0.1   theboss.local theboss'
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Disable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        enabled: false
        state: stopped
      become: true

    - name: Unlink resolv.conf
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
      become: true
    
    - name: Create new resolv.conf
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
      become: true

    - name: Start and enable hostapd
      ansible.builtin.service:
        name: hostapd
        state: started
        enabled: true
      become: true

    - name: Start and enable dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: started
        enabled: true
      become: true

  rescue:
    - name: Handle task failure
      ansible.builtin.debug:
        msg: "A task in the networking configuration block failed"
    - name: Increment failure counter
      ansible.builtin.set_fact:
        failure_counter: "{{ failure_counter | default(0) | int + 1 }}"
