---
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ./config:/config
      - /mnt/Stash/Library:/Library
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped
